### ISSUE TITLE
DPL-374 Plate summary page improvements [C=S, V=3]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3604]
**User story**
The plate summary page in Sequencescape contains a lot of the information that the lab teams are recording manually on worksheets. The feature doesn't seem to be well used, and I think this is because it has some UX issues and could be easier to find. This story is to make a few simple improvements to start getting users more engaged with this page. Hopefully it will lead to feedback and further improvements.

**Who are the primary contacts for this story**
Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Samples list is automatically collapsed (it hides the I-think-more-useful information at the bottom of the page)
- [ ] The list of labware at the bottom of the page should be ordered usefully, according to the line of descent. (If order can be consistent with [the algorithm behind the kanban page](https://github.com/sanger/limber/blob/730237614020b9131f6dcd751e5c829497018c98/app/models/pipeline_list.rb#L42), that would be good, although that comes from the Limber pipeline config, so may not be possible). 
- [ ] Include link to this page from labware page in Limber
- [ ] Include link back to labware page in Limber

**References**
See other stories with the 'Plate tracking' label.

**Additional context**
Other ideas for future:
- Include Metadata and Comments from all labware on the page (is this what the 'Metadata' section at the top is meant to do?)
