### ISSUE TITLE
DPL-377 'library_complete' and 'pool_released' events [C=M, V=4]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3607]
**User story**
As a DNAP team lead I would like the 'library_complete' event to fire when libraries are 'charged and passed' in Limber, as this is more representative of when the library is complete than the current trigger (when the multiplexed library tube is passed), which can be delayed for long periods of time. 

I would also like to add a new event type called 'pool_released', fired when the multiplexed library tube is passed, to allow more detail in the reports.

**Who are the primary contacts for this story**
Liz E, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] The library_complete event (Event WH) is triggered by the 'Charge and pass' button being clicked in Limber, instead of the current trigger (which is when the multiplexed library tube is passed)
- [x] The current trigger (when the multiplexed library tube is passed) is retained as an event point - but the event fired here is called 'pool_released' instead.
- [x] Event documentation table at the bottom of this page is updated - https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=137076202

**References**
This came out of this story - https://github.com/sanger/General-Backlog-Items/issues/169

**Comment by JamesGlover** [comment]
We also have an event when the tube is scanned in to the sequencing pipeline freezer, indicating when it has actually left the library prep lab and is queued up for sequencing.

https://github.com/sanger/sequencescape/blob/01815b18752803118beaf7a8a833764967f380e3/app/models/labwhere_reception.rb#L66-L75

When pulling these events back you'd need to filter for the correct location, based on the location_barcode metadata. Not sure what the barcode for postman pat is.
