### ISSUE TITLE
DPL-400 library_complete event for all Limber pipelines

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3615]
**User story**
As a DNA Pipelines team lead, I would like the library_complete event to be fired across all Limber pipelines, so that I can use it consistently as a timestamp in my TAT (turn around time) reports.

**Who are the primary contacts for this story**
Liz E, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] 'library_complete' event is fired for the following tubes (in addition to those it currently fires for):
    - LDS Custom Pool Norm ('Duplex Seq' pipeline)
    - LB Custom Pool Norm ('Custom Pool' pipeline - LCMB)
- [ ] **also for the following?? TBC**
    - CLCM DNA Pool Norm ('CLCM Custom Pooling for DNAseq' pipeline)
    - CLCM RNA Pool Norm ('CLCM Custom Pooling for RNAseq' pipeline)
    - LCA Custom Pool or Standard MX ('Cardinal' pipeline, and others for Standard MX)
    - LTN Custom Pool Norm ('Targeted NanoSeq' pipeline)
- [ ] Event subjects include the stock_plate, as that is important for the TAT reporting (see https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=137076202)
- [ ] Rest of event subjects and metadata is as similar as possible to that included in the existing library_complete events
- [ ] Event documentation at the bottom of this page - https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=137076202 - is updated if needed

**References**
As part of https://github.com/sanger/sequencescape/issues/3607, the 'library_complete' event will be renamed to 'pool_released'. This story refers to the event that is currently when multiplexed library tubes change state to 'passed' - whether it has been renamed already or not.

**Additional context**
This event currently fires on state change to 'passed', for tubes where the Purpose Type is 'IlluminaHtp::MxTubePurpose'. It does not currently fire on any multiplexed library tubes with a different Purpose Type.

Assumption - these new events will only be created going forward, not back-populated for historic events.

**Comment by ElizabethEasthope** [comment]
Katy,  please do include all of the named pipelines in searches to ensure the data will be retrieved for these as well as the original 2 pipelines (Dupseq and LCMB).
thanks
