### ISSUE TITLE
DPL-418 Refine read-length tracking

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3629]
**User story**
As a sequencing tech I would like refined read length tracking to remove the need for providing additional information in comments.

See: https://github.com/sanger/sequencescape/issues/3628 when writing migrations, if its not done already

**Who are the primary contacts for this story**
Tris
Siobhan
Rich R

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Bulk submission templates should have options read_2_length column, similar for web interface
- [ ] If reverse_length is not filled in, populate it with the read_length value.
- [ ] Persist as request_metadata
- [ ] Sequencing inboxes should replace single read_length value with: forward_read;index_read1;index_read2;reverse_read reverse_read fallsback to read1 if value is null to support historic data
- [ ] index_read1 based on maximum tag1 length
- [ ] index_read2 based on maximum tag2 length (0 if no tag2)
- [ ] Inbox should contain clear description of this format
- [ ] Remove unwanted columns Submission, Product Line, Previous Requests, Submitted at - Previous requests and submitted at in particular have a decent chunk of supporting code that might be able to be removed. (Also in https://github.com/sanger/sequencescape/issues/3628 so may be done)
- [ ] Remove Dual-index column, as now redundant.
- [ ] Reverse read-length column in flowcell message should be populated by reverse_read

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
