### ISSUE TITLE
DPL-395-2 Track external batches (searching)

### ISSUE THREAD

**Issue by harrietc52** [sanger/sequencescape#3630]
**User story**
As a member of the Heron team, I would like to search on reagant batches (coupled with https://github.com/sanger/General-Backlog-Items/issues/193)

**Who are the primary contacts for this story**
Barbora @KatyTaylor @harrietc52 

**Acceptance criteria**
To be considered successful the solution must allow:

- [ ] There is somewhere in the LIMS that shows me all the reagent batches for the whole line of plates in the pipeline (think the plate summary page in SS already meets this requirement)
- [ ] Given a batch number of a particular reagent, I can find all plates it was used on - this should be presented in a format that is usable by your average lab member (i.e. a user interface or downloadable csv - not raw SQL)
- [ ] From any plate in the pipeline, I can easily find its associated 'input plate'

**Dependencies**
https://github.com/sanger/General-Backlog-Items/issues/193

**Comment by KatyTaylor** [comment]
A basic form of the search page is implemented in https://github.com/sanger/sequencescape/pull/3627

This adds a new tab, 'Search', to the Sequencescape navigation bar. It also allows prepopulation of the search terms via URL query parameters - the idea is that there could be a link where the custom metadata is displayed in Limber, 'find other labware with this metadata', or similar, that could take you to the page with the 'key' and 'value' search terms pre-populated.

The above pull request also places the new tab behind a feature flag, so the new tab can be toggled on / off as needed. The URL to control this is the normal Sequencescape base URL followed by `/flipper`,  and you have to be an administrator to access it.

I'm creating a new story to handle merging the multiple existing search pages into one 'Advanced Search' page.
