### ISSUE TITLE
EPIC:- DPL-678 - Bioscan - Creation of asynchronous job to generate the compound sample,  the mBrave file and write an export to traction message onto RabbitMQ

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#3754]
**User story**
As PSD we need to create a Sequencescape job to perform the steps required to generate a compound sample and mBrave file from the samples in the XP tube, and to write an export message to pass the tube and compound sample info to Traction. 

**Who are the primary contacts for this story**
Andrew S
Harriet C

**Who is the nominated tester for UAT**
TBC

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] triggering of the job from a Limber view (see research story [here](https://github.com/sanger/sequencescape/issues/3753))
- [ ] fetching the sample information for the XP tube
- [ ] creation of a compound sample
- [x] creation of the mBrave file
- [x] creation of the RabbitMQ message for export of the tube and compound sample into Traction
- [x] updating the tube state (or export state) with progress and additionally any error messages if fails, and possible adding log comments to XP tube

**Dependencies**
This story is blocked by the following dependencies:
- #3753 

**Sub-tasks**
This EPIC has the following sub-tasks:
- https://github.com/sanger/tol-lab-share/issues/70
- https://github.com/sanger/General-Backlog-Items/issues/374
- https://github.com/sanger/traction-service/issues/1255
- https://github.com/sanger/General-Backlog-Items/issues/370
- https://github.com/sanger/General-Backlog-Items/issues/377
- https://github.com/sanger/tol-lab-share/issues/71
- https://github.com/sanger/tol-lab-share/issues/72
- https://github.com/sanger/tol-lab-share/issues/102
- https://github.com/sanger/tol-lab-share/issues/73
- https://github.com/sanger/limber/issues/1617

**Additional context**
As input we probably just need to know the XP tube id.
As we need the 9216 samples for both the compound sample creation and the mBrave file creation it makes sense to fetch those once.
