### ISSUE TITLE
Y24-040 Specify 2 lanes only for NovaSeq X Plus 1.5B flowcell

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#4068]
**User story**
As a High Throughput Short Read Sequencing team lead (Tris), I want the system to check the NovaSeqX submitted samples for 'Flow cell Type' and 'Permitted number of lanes/read lengths' before a sequencing batch is created SO THAT the additional monetary expense incurred due to incorrect sample selection can be avoided.

For the NovaSeqX there following flow cell options:

1. 1.5B (Two lane), - _Primary requirement for this story_
2. 10B (Eight lane), 
3. 25B (Eight lane)

**Who are the primary contacts for this story**
Tris

**Who is the nominated tester for UAT**
Tris

**Acceptance criteria**
To be considered successful the solution must allow:

1. If I select requests where the **flow cell requested** is 1.5B, I am only permitted to create a batch for exactly 2 requests i.e. 2 lanes (no more no less).
2. If I select requests where the flow cell requested is something else, behaviour is unchanged i.e. the system allows for 8 lane requests for both 10B and 25B flow cell types.  NB: There was a similar requirement for NovaSeq 6000 added to the story https://github.com/sanger/sequencescape/issues/3770. It would be worth confirming if the change was implemented or still needs to be implemented.
3. If I select requests where the requested **read lengths are different**, I am only permitted to create a batch for the same read lengths. (This is similar to that in NovaSeq 6000 pipeline)
4. If I select requests in a different sequencing pipeline inbox, the behaviour is unchanged.
5. I cannot create a batch containing requests of **different types of flow cells types**(10B, 25B, 1.5B) (NB: Similar to https://github.com/sanger/sequencescape/issues/3819. Need to confirm if can be reused)
6. I can see an updated message prompted on the message banner informing about the (Can reuse similar wording as in NovaSeq 6000 pipeline)
- permitted lanes
- limitations around mixing flow cell types based on users' selection
- limitations around mixing read lengths based on users' selection

![image](https://github.com/sanger/sequencescape/assets/115623404/6c04f92f-4ae8-436f-98cc-36d9e6b4e8e5)

**Additional context**

Comments from Tris and RT raised [RT799336](https://rt.sanger.ac.uk/Ticket/Display.html?id=799336)

1. When selecting requests from the NovaSeq X pipeline inbox the number of lanes permitted for a 1.5B flow cell should be 2 (no more no less).
2. Currently, SS is restricting batch creation. Also, the message displayed is not relevant to the scenario supporting 1.5B flow cells. 
3. Restrict mixing of requests (sample pool) for different types of flow cells  (10B, 25B, 1.5B) on the same batch. The intention is to build capability for error handling (Good to Have)

Blocking dependency
[#4135](https://github.com/sanger/sequencescape/issues/4135)

**Comment by KatyTaylor** [comment]
Previous relevant PR - https://github.com/sanger/sequencescape/pull/3794/files

**Comment by KatyTaylor** [comment]
The 'Flowcell type' referenced by the story is recorded in the `request_metadata` table as `requested_flowcell_type`.

**Comment by KatyTaylor** [comment]
I think the requirement "Restrict mixing of requests (sample pool) for different types of flowcells (10B, 25B, 1.5B) on the same batch." is already met by the below code, although I haven't tested it.

```
  def requests_have_same_flowcell_type
    unless pipeline.is_flowcell_type_consistent_for_batch?(self)
      errors.add :base, "The selected requests must have the same values in their 'Flowcell Requested' field."
    end
  end
```

**Comment by KatyTaylor** [comment]
@SujitDey2022 could we have some acceptance criteria? Would it be something like:

When selecting requests from the NovaSeq X pipeline inbox (Pipelines tab > NovaSeqX PE):
- If I select requests where the 'Flowcell Requested' is 1.5B, I am only permitted to create a batch if I select exactly 2 requests.
- The error message displayed is more relevant to this scenario (TODO: what is the existing error message, and what should it be?)
- If I select requests where the 'Flowcell Requested' is something else, behaviour is unchanged.
- If I select requests in a different sequencing pipeline inbox, behaviour is unchanged.
- I cannot create a batch containing requests of different types of flowcells (10B, 25B, 1.5B) (think this is already implemented).

**Comment by SujitDey2022** [comment]
Thanks @KatyTaylor I was intending to refine the story and acceptance criteria Today. Will get it done...

**Comment by neilsycamore** [comment]
@KatyTaylor @SujitDey2022 
Conversation 15/03/2024 tw6 & tkb
•              Will you always use 2 flow lanes or is there a possibility that only 1 flow lane could be used? 
For the NovaSeq X Plus there will only be the following options: 1.5B (Two lane), 10B (Eight lane), 25B (Eight lane)
•              When do you foresee the next 1.5B flowcell run happening? 
Our top priority is to get this validation pushed through somehow but after that I have no further visibility but as this is now a product which Illumina provide II expect Faculty will be wanting this option shortly.

**Comment by SujitDey2022** [comment]
@KatyTaylor added an additional read length condition based on feedback from Tris.

**Comment by BenTopping** [comment]
**Work breakdown**

1. **(size: S)** I can create batches of 2 for NovaSeqX
  - [We can change the pipeline min_size in the record loader](https://github.com/sanger/sequencescape/blob/develop/config/default_records/pipelines/default_records.yml#L38) and manually change this value in production via the rails console. This will allow batches of size 2-8 to be created.
  - We can't limit NovaSeqX to exactly batches of 2 or 8 lanes without further work described in work breakdown 3. 
  - This work will prevent tickets to psd-help for overriding existing validation.

2. **(size: S)** If I select requests where the requested read lengths are different, I am only permitted to create a batch for the same read lengths.
  - This will be similar to [DPL-783](https://github.com/sanger/sequencescape/issues/3819) [PR](https://github.com/sanger/sequencescape/pull/3831)
  - **Q:** Is this for all pipelines or just NovaSeqX?

3. **(size: L)** Fine-grained batch creation based off request or other data.
  - This will allow us to add additional validation to batch creation other than just batch size.
  - This work can cover NovaSeqX initially but should be setup in such a way that other pipelines can implement it.
  - When selecting a request in a batch check the validation parameters and grey out subsequent invalid requests. e.g. in this case selecting a 1.5B request greys out 10B requests.
  - This will set up but not complete [DPL-700](https://github.com/sanger/sequencescape/issues/3770) to be completed relatively easily.

**Comment by seenanair** [comment]
Following the discussion with @BenTopping , @KatyTaylor  and @dasunpubudumal  the scope of the story is defined as follows

Batch creation validation in NovaSeq X:
  When selecting requests from the NovaSeq X pipeline inbox (Pipelines tab > NovaSeqX PE):

- [ ] If I select requests where the 'Flowcell Requested' is 1.5B, I am only permitted to create a batch if I select exactly 2 requests.
- [ ] The error message displayed is more relevant to this scenario (TODO: what is the existing error message, and what should it be?)
- [ ] I can see an updated message prompted on the message banner informing about the (Can reuse similar wording as in NovaSeq 6000 pipeline)
- [ ] If I select requests where the 'Flowcell Requested' is something else, behaviour is unchanged.
- [ ] If I select requests in a different sequencing pipeline inbox, behaviour is unchanged.

This story is dependendant on [DPL-783](https://github.com/sanger/sequencescape/issues/3819)  can only be implemented after the completion of it.

**Comment by SujitDey2022** [comment]
Hi @seenanair, I was looking your comment above and noticed that the story that you mentioned as a pre-requisite DPL-783 is already completed. Is the referenced story number correct?

**Comment by seenanair** [comment]
> Hi @seenanair, I was looking your comment above and noticed that the story that you mentioned as a pre-requisite DPL-783 is already completed. Is the referenced story number correct?

@SujitDey2022 Sorry, corrected it. The pre-requisite is [Y24-121](https://github.com/sanger/sequencescape/issues/4135) which Dasun is currently doing.
