### ISSUE TITLE
Y24-194 - LCM WGS/EM-Seq - Pipeline configuration and integration test

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#4199]
**User story**
As Scott and Sara we would like tracking developed for the new LCM WGS/EM-Seq pipeline. A process map and associated documentation contain the details required.

**Who are the primary contacts for this story**
Scott G (R&D)
Sara W (Lab ops)

**Who is the nominated tester for UAT**
TBC

**Acceptance criteria**
Sub-stories have been created that should cover this story. The following acceptance criteria are for checking everything is joined up and tested:
- [x] Integration Suite test for whole pipeline, including the same samples going down both the EM-Seq and WGS branches.
- [ ] Confirm Submission names, request type and library type names with stakeholders

**Dependencies**
This story is divided into two stories for EMSeq and WGS branches and a common initial part up to the Adp Lig plate. Transitive dependencies have been added here as well to find them easier.

- [x] [Y24-271 - Configuration and integration test for the start of LCM Triomics Pipeline](https://github.com/sanger/sequencescape/issues/4291)
- [x] [Y24-266 - LCM Triomics Pipeline configuration and integration test for EMSeq branch](https://github.com/sanger/sequencescape/issues/4288)
- [x] [Y24-267 - LCM Triomics Pipeline configuration and integration test for WGS branch](https://github.com/sanger/sequencescape/issues/4289)
- [x] [Y24-268 - Create a presenter for automated submission for WGS branch on Adp Lig plate](https://github.com/sanger/sequencescape/issues/4290)
- [ ] [Y24-460 - Confirm and update fragment sizes for WGS Branch - Automated Submission](https://github.com/sanger/limber/issues/2073)

**References**
This story has a non-blocking relationship with:
- [Y24-196 - LCM WGS/EM-Seq - Research - Test pipeline configuration](https://github.com/sanger/sequencescape/issues/4200) This is the research story about the branch point.
- [ LCM WGS/EM-Seq Bed verifications](https://github.com/sanger/limber/issues/1782) This is the following story for bed verifications.

**Additional context**
See the following documents for detailed information (e.g. steps and plate purposes):
[LucidChart Process Diagram](https://lucid.app/lucidchart/b71a82e4-ca5c-4fb4-a2bb-4f16e21f6376/edit?viewport_loc=-28747%2C-538%2C2198%2C1172%2CpY0tJQ3FKvrSt&invitationId=inv_80dd70e7-82ea-4415-b592-c507c64af359)
[Overview document](https://docs.google.com/document/d/1HcQFBiFNBCYqKC6FDYGJX6FV-XbLYxrRJfJV_L14hj4/edit?usp=sharing)
[CLCM Multiomics document](https://docs.google.com/spreadsheets/d/1GMRGzKCdcvoSwdBWtTuz674x0gZd_YefIhRuyXRZkEs/edit?usp=sharing)

Mostly this story is standard SS and Limber configuration.
These are the tricky bits I can see (also see docs above):
1. Submissions - Initial submission is on the Lysate plate at the start, for DNA prep (RNA branch may be added later). Then part way along this brnaches into WGS and EM paths. Both branches will always happen, in parallel. You cannot use one submission all the way through because of this later branch. But as both will always happen for all samples then you don't want to have to wait on the SSR to manually create submissions at the branch point. Possibly create an automatic submission to branch off the EM path? Have to try out some options and see what works best.
2. There are several places where they have annotated bed verifications that want to check multiple plates in advance. We can't do bed verifications that involve transfers that go A->B->C, but we should be able to do verifying ones that check plates are in specific positions. But only if LIMS already knows about the barcodes of those plates, so they'd have to be set up in advance. Includes crossing the branching point. 
3. They would like to print out labels in advance for these steps that include the branching. I'm not sure we can do that.

The research story for the branching point is [Y24-196 - LCM WGS/EM-Seq - Research - Test pipeline configuration](https://github.com/sanger/sequencescape/issues/4200)

**Comment by yoldas** [comment]
We have updated the library types based on the feedback by email on 27 November.

However, we still need to confirm the WGS submission options, which will be finalised by the story [Y24-460 - Confirm and update fragment sizes for WGS Branch - Automated Submission](https://github.com/sanger/limber/issues/2073)

We have created the following stories as enhancements for later.

[Y24-463 - Custom text for robot start buttons](https://github.com/sanger/limber/issues/2075)
[Y24-464 - Create multiple plates in pending state at once](https://github.com/sanger/limber/issues/2076)
[Y24-489 - Show the robot button Bravo LCMT DNA Adp Lig => LCMT DNA Lib PCR after the WGS branch submission](https://github.com/sanger/limber/issues/2100)

**Comment by yoldas** [comment]
I have set superseded_by on the old submission: `Limber-Htp - LCM Triomics EMSeq` in UAT; the replacement is `Limber-Htp - LCM Triomics` . 

Note that the request type for the `Limber-Htp - LCM Triomics` submission is still 'LCM Triomics EMSeq' . This is because the pipeline starts with EMSeq and branches off for WGS later and (RNASeq in the future).

**Comment by yoldas** [comment]
In UAT, LCMT Lysate page did not give option to add the child LCMT DNA Frag plate. I have found that the old Library Type LCM Triomics EMSeq was used for the submission on the Lysate plate; it should be emSEQ instead. I have replaced the library types of the LCM Triomics requests on all wells, updated the library type on request metadata and removed the old request_type_library_type and library_type records.

**Comment by yoldas** [comment]
We had an issue with the local run of integration suite does not show WGS branch and manual transfer does not change the state. I have found that this was because Adp Lig was set to be an input plate. This has been fixed in Y24-194 [PR] Fix LCMT DNA Adp Lig purpose record #4608

**Comment by yoldas** [comment]
We still have an issue with the LCMT Lysate barcode labels printed form Sequencescape. This is work in progress: Y24-194 [PR] LCMT Lysate barcode label #540

**Comment by yoldas** [comment]
Search wip files to unwip.

```
cd sequencescape
find . -name '*.wip.yml'| grep lcm_triomics

./config/default_records/submission_templates/014_lcm_triomics_submission_templates.wip.yml
./config/default_records/request_types/018_limber_lcm_triomics_request_types.wip.yml
./config/default_records/plate_purposes/013_lcm_triomics_plate_purposes.wip.yml
./config/default_records/product_catalogues/013_lcm_triomics_catalogue.wip.yml
```

```
cd limber
find . -name '*.wip.yml'| grep lcm
./config/pipelines/high_throughput_lcm_triomics.wip.yml
./config/purposes/lcm_triomics.wip.yml
ay6@mib117536s limber % find . -name '*.wip.yml'| grep lcm_triomics
./config/pipelines/high_throughput_lcm_triomics.wip.yml
./config/purposes/lcm_triomics.wip.yml
```
