### ISSUE TITLE
Y24-492 - Tol BIOSCAN need a digital link between identifiers to enable them to report on the samples they have processed

### ISSUE THREAD

**Issue by sabrine33** [sanger/sequencescape#4537]
**Context**
I had a chat to Alex and we had a look at SequenceScape to pinpoint the exact data we are looking to aggregate and access – please see the screenshot attached in combination with the simplified process map (we don’t really use these much in our team, so let me know if it is detailed enough).
 
Essentially we are asking for the data highlighted (from SequenceScape) to be pushed to multilims warehouse and we (Alex and TOLP) can pick it up from there, as long as we are able to have the plate IDs linked and have access to it.

**What we know**
All of the data highlighted by ToL in the image on the left is available in the sample table in the MLWH database.
The only data that is not present is the details of the transfer/s between the "LILY-96 Stock" plate to the "LBSN-96 Lysate" plate.

The sample tracking report is meant to be general for all short read pipelines - we will **not** include pipeline specific details into this report as it will get unusable. But we can consider re-using the ideas/views etc to build something specific for individual pipelines.

**Acceptance Criteria**
What we would like:

Consider the questions below in conjunction with the stakeholders.

- [ ] Given most of the data is already there - how important is the transition data to the Lysate plate for ToL? Is there another way of answering the question they need it for? A. They want to cherrypick from the Lysate plates. So given lists of samples they want the plate barcodes and well locations for those samples in the Lysate plates. This is not in MLWH.
- [ ] What is the final report output they are trying to generate? A. Cherrypicking lists, plus multiple reporting queries. Solution requires the data be in MLWH.
- [ ] Where is the final report going to be accessed from Tableau or MLWH or both? A. Multiple queries and reports. They can create those if the data is available.
- [ ] Are the alternatives to this transition data being in MLWH that could be considered? e.g. RabbitMQ, SS REST API, direct access to SS database, something else? A. The information is in the SS database. As they want multiple queries and reports that may change, best they have access to the data. Not generally a good idea to give direct access to the SS database.
- [ ] If we are to export this plate transition data to MLWH, should we export all intermediate plate transition data to MLWH ? (Q. for PSD) A. Thinking a more targeted approach is more sensible. Either all 'stock' intermediate plates, or control specifically by setting a flag in the purpose configuration. Risk is unknown effects on reporting if samples have more than one stock_resource.
- [ ] If we do export this plate transition data to MLWH, in what form? e.g. mlwh_events, a dedicated transition and plate tables, or something else.... A. At manifest upload we write a Message for each row (well) to the MLWH to write a stock resource record. If we can use this Message system at the point when we create the Bioscan Lysate plates, we could write them into MLWH then.

**Who are the primary contacts for this story**
Lyndall P

**Comment by stevieing** [comment]
[simple process map - BIOSCAN sequenceScapeMLWH.pdf](https://github.com/user-attachments/files/17991053/simple.process.map.-.BIOSCAN.sequenceScapeMLWH.pdf)

![Image](https://github.com/user-attachments/assets/bdfc3fdf-4d7f-4763-b825-e50bfdf98659)

**Comment by TWJW-SANGER** [comment]
@stevieing I've updated the criteria for this. Could you see if it makes sense? Thanks.

**Comment by andrewsparkes** [comment]
For background:
'LILY-96 Stock' is the initial insects in ethanol stock plate from the customer.
We take this, do a Lysate prep (separate DNA/RNA from the insects) and create the 'LBSN-96 Lysate' plate on a robot. During this process we add 2 new controls, one in a fixed location, one random. The random one might replace a sample for that destination well, otherwise it is a stamp.
4 lysate plates get combined into a 384-well plate, which is tagged with 1 of 24 unique tag sets.
They build up 24 x 384-well plates like this using the 1-24 tag sets, then pool.
Pooling is 2 steps, first each 384-well plate is pooled into a tube (= 24 tubes) then the 24 tubes are pooled into 1, containing up to 9216 samples + controls.
This final 'LBSN-9216 Lib PCR Pool XP' tube can be viewed in Limber LIMS and an 'mBrave' report can be exported. This contains up to 9216 rows of information, one for each sample in the final pool tube, including it's customer supplier sample name, customer plate identifier and the tag information.

I'm not understanding from the story _why_ they need the transition data between the stock and lysate plates. It will just be a straight stamp other than for any sample displaced by the random control. Do they want to know which samples were displaced? Do they want to know which samples went forward to pooling? (that's in the mBrave report).

**Comment by andrewsparkes** [comment]
Lyndall email trip note says she is off till 4th Feb.

**Comment by andrewsparkes** [comment]
### Aim
Push LBSN-96 Lysate stock plate to MLWH as a stock_resource

### Research
See `app/models/sample_manifest/uploader.rb`
In this class we upload sample manifests and write the information to the MLWH.
See line 61 upload.register_stock_resource
Which calls method `register_stock_resource` in class `app/sample_manifest_excel/sample_manifest_excel/upload/base.rb`
on line 109
This calls `register_stock!` on `stock_receptacles_to_be_registered` which is `rows.select(&:sample_created?).map(&:asset)`
The `sample_created?` method checks that `sample.save` worked on initial save of the asset. In our case for the Lysate plate the samples should exist already. 

Q. Do the 2 control samples automatically get written to the MLWH already as they get created over the SS api? 
A. Does not look like it.

If not (maybe it's only for manifest samples) then we need to create them in MLWH.

To create stock_resource rows in MLWH:
See `app/models/asset.rb` line 156 `register_stock!` method
This runs:
`Messenger.create!(target: self, template: stock_message_template, root: 'stock_resource')`

Which uses `app/models/messenger.rb `(so 1 message per well)

For a well, `stock_message_template` is a `WellStockResourceIO`
See `app/models/api/messages/well_stock_resource_io.rb`
This appears to create the stock resource and associated records i.e. sample, but not clear.

Q. Can we use this as is? Or do we need a custom version?
A. Possibly, need to check if it behaves if samples already exist

Q. What happens in the unified warehouse on receipt of this message?
where is the message received? what does it do for a plate well if the sample already exists?

So use something like this for the receptacles in the LBSN-96 Lysate plate (labware) (needs to only register those receptacles that have aliquots with samples):
```
receptacles = Receptacle.where(labware:).joins(:aliquots).where('aliquots.sample_id not null')
receptacles.each { |r| r.register_stock! }
```

Labware creator for this step in Bioscan is the `StampedPlateAddingRandomisedControls` one, see `app/models/labware_creators/stamped_plate_adding_randomised_controls.rb`
This calls `create_plate_from_parent!` in the base class `app/models/labware_creators/base.rb` to create the plate.

```
Sequencescape::Api::V2::PlateCreation.create!(
    child_purpose_uuid: purpose_uuid,
    parent_uuid: parent_uuid,
    user_uuid: user_uuid
)
```

The labware creator also has a method `create_control_sample(control, well_location)` to make the control samples. Calling:
```
Sequencescape::Api::V2::Sample.new(
  name: sample_name,
  sanger_sample_id: sample_name,
  control: true,
  control_type: control.control_type
)
```
I cannot see anything in the code that automatically registers the new sample in the MLWH.
It appears to be triggered only for manifest uploads.

### Possible solutions:
    1. Limber and SS: we could modify the plate creation endpoint called by the labware creator to include an additional optional flag taken from purpose config to 'register in mlwh' then trigger the Message creation to add that stock plate to the MLWH. Validate and do not allow for anything other than stock plates. Default (if no flag) is to not do it. Then on SS side the endpoint checks if flag present, and cycles well receptacles in plate to register_stock!. This needs to create the sample rows for the newly generated controls, but not duplicate the samples as they should already exist from the manifest upload.
**Issue**: plate is still in pending state here. Technically the samples are not in it yet.
**Comment**: I prefer this option as we're doing plate creation here. 

    2. Limber: the state changer for the lysate plate (currently this is the generic `StateChangers::AutomaticPlateStateChanger`) uses work completion code to close off the requests for lysate prep. We could also use this to trigger the creation of the message to the MLWH on the SS side. Could add an optional flag passed via the api endpoint for work completion to do this.
**Issue**: this only happens once the plate is transferred into (transition to passed state). This may be later than they would prefer. 
**Comment**: I don't think this solution fits as work completion is about closing off requests rather than creation of samples and plates.


General Questions/Issues:
    1. Does the MLWH Message receipt allow a sample to have 2 stock plate entries? And does it skip sample setup for those samples that already exist, whilst still inserting the stock_resource row for that sample?
    2. Do we need a code change to the unified warehouse message receipt code?
    3. Will having two stock plates for a sample break any reporting queries?

**Comment by andrewsparkes** [comment]
Testing:

These are the details of an attempt to create and send a message for the insert of a second stock resource row for the same sample.

1. Manually create a LILYS-96 Stock plate sample manifest with 96 samples in it [barcode I generated: SQPU-201897-D] and upload it [Must be manual so as to trigger the inserts to MLWH on upload of the sample manifest. The UAT action to generate a plate does NOT do this stock resource insert.]
2. Check MLWH for sample and stock_resource rows for LILYS-96 Stock plate [e.g. in A1 = sample id 7779264, uuid "88c700a0-f5e1-11ef-a337-02427e19310d", study id 5893, uuid "fec8a1fa-b9e2-11e9-9123-fa163e99b035"]
3. Submit the plate for Bioscan lysate prep either manually or via UAT action testsubmission [submission 171146]
4. In Limber run the plate to create [generated Lysate plate SQPU-201898-E] AND transfer into the Lysate plate [SQPU-201897-D in bed 9 = 580000009659, Lysate SQPU-201898-E in bed 14 = 580000014851]
5. Get well uuid and id for the lysate plate well in A1 (checking not replaced by a control), plus sample uuid and it's study id [well id = 54047737, well uuid = "8104c070-f5e4-11ef-8a0b-02427a4c9fb2",sample id 7779264, uuid = "88c700a0-f5e1-11ef-a337-02427e19310d", study id 5893, uuid "fec8a1fa-b9e2-11e9-9123-fa163e99b035", Stock resource row does NOT exist in DB yet as code does not currently insert stock resource rows for intermediate plates. Note sample is same as for LILYS plate.]
6. Create json for the Message to create a stock resource for the Lysate well (note formatting, timestamps are strings, no rockets use colons, null not nil):

```
{
    "stock_resource": {
        "stock_resource_uuid": "8104c070-f5e4-11ef-8a0b-02427a4c9fb2",
        "stock_resource_id": 54047737,
        "created_at": "Fri, 28 Feb 2025 11:07:07.000000000 GMT +00:00",
        "updated_at": "Fri, 28 Feb 2025 11:12:25.000000000 GMT +00:00",
        "labware_type": "well",
        "labware_coordinate": "A1",
        "machine_barcode": "SQPU-201898-E",
        "human_barcode": "SQPU-201898-E",
        "concentration": null,
        "initial_volume": null,
        "current_volume": null,
        "snp_count": null,
        "pico_pass": "ungraded",
        "gel_pass": null,
        "samples": [
            {
                "sample_uuid": "88c700a0-f5e1-11ef-a337-02427e19310d",
                "study_uuid": "fec8a1fa-b9e2-11e9-9123-fa163e99b035"
            }
        ]
    },
    "lims": "SQSCP_ST"
}
```
7. Send the message in UAT to the MLWH:
http://ware-uat.psd.sanger.ac.uk:15672/#/queues/test/psd.mlwh.multi-lims-warehouse-consumer
(access details in credentials)
Use PUBLISH option on that page. No headers or other params, just fill in the Payload field with the above json.

NB. THE MESSAGE PROCESSING IS SLOW, be patient.
I then see 2 rows for the same sample on the stock_resource table. Note same id_sample_tmp, different well resource ids

id_stock_resource_tmp,last_updated,recorded_at,created,deleted_at,id_sample_tmp,id_study_tmp,id_lims,id_stock_resource_lims,stock_resource_uuid,labware_type,labware_machine_barcode,labware_human_barcode,labware_coordinate,current_volume,initial_volume,concentration,gel_pass,pico_pass,snp_count,measured_gender
136919,"2025-02-28 14:37:33","2025-02-28 14:37:38","2025-02-28 14:25:05",NULL,3781305,26,SQSCP_ST,54047641,ce009a98-f5df-11ef-adaa-0242fffcc087,well,SQPU-201897-D,SQPU-201897-D,A1,NULL,NULL,NULL,NULL,ungraded,NULL,NULL
137015,"2025-02-28 11:12:25","2025-02-28 15:59:56","2025-02-28 11:07:07",NULL,3781305,26,SQSCP_ST,54047737,8104c070-f5e4-11ef-8a0b-02427a4c9fb2,well,SQPU-201898-E,SQPU-201898-E,A1,NULL,NULL,NULL,NULL,ungraded,NULL,NULL

This proves that we can add messages for the Lysate plate without any Unified Warehouse changes being required. It allows the same sample to have 2 stock_resource rows.
