### ISSUE TITLE
Y24-495 - As a TL I want to know when creating or updating sample metadata in the EGA/ENA fail so that we can catch errors early.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4540]
**Description**
As a TL I want to know when creating or updating sample metadata in the EGA/ENA fail so that we can catch errors early.

**Acceptance Criteria**

- [ ] Failures when calling the ENA API are logged at an error level with complete details of payload and responses.
- [ ] Failures when calling the ENA API are flagged in our monitoring / exception system so the team is aware of them.
- [ ] Failures updating the ENA API for a given sample are indicated on the sample/plate level in SequenceScape UI so that users are aware there has been a problem.

**Background**
A robust application cannot ignore errors or failure paths- especially where they relate to data integrity. That we do have these issues vexes me.
At a (very) minimum the failure with supporting information must be logged.
