### ISSUE TITLE
Y24-527 - As a TL (Tris B) I would like to upload sample information on "user prepared" libraries so that they can be validated for sequencing on the Element Aviti sequencer.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4575]
**User story**
As a TL (Tris B) I would like to upload sample information on "user prepared" libraries so that they can be validated for sequencing on the Element Aviti sequencer.

This User Story has outstanding questions **In Bold** that need refinement.
This is an EPIC and likely needs breaking up into smaller user stories.

**Who are the primary contacts for this story**
Tris B
Mike Q
David J
See our Confluence project page for "Element Aviti"

**Who is the nominated tester for UAT**
Tris B

**Acceptance criteria**

Consider if these features can be _featured flagged_ to decouple testing and deployment.

To be considered successful the solution must allow:
- [ ] User needs to specify which Study and Cost code is being used either explicitly or by starting from a Study page
- [ ] User will specify the Sequencing Kit used from a drop down. **List of Options required**
- [ ] User will specify the Read Length from a drop down **List of Options required**
- [ ] User will specify if a Custom primer is required [Yes/No]
- [ ] If a Custom primer is required 1. Display text "Supply 20ul at 100 uM" **Supply 20 ul of primer to whom? where? when? Is this message for Tris or faculty.** 2. Input details of which primer e.g. R1/R2/i1/i2  **List of Options required ?**
- [ ] If a Custom primer is not required **What do we record in the LIMS? NULL or something else? What do NPG need?**
- [ ] User will enter Library type If not an Illumina library from a dropdown **Options needed** **CHECK - don't NPG need to know which Illumina library type anyway?**
- [ ] User will enter Library pool concentration in nM **CHECK - valid ranges?**
- [ ] User will enter qPCR recommended checkbox **CHECK**
- [ ] User will enter "Low complexity"  checkbox Y/N
- [ ] If "Low complexity" is Yes then User will answer "Are there more than 68 different i7 barcodes" checkbox Y/N **CHECK - is this a validation?**
- [ ] User will answer "Is phiX required [Yes/No]" checkbock
- [ ] If "Is phiX required" is Yes User will answer "Required phiX concentration" [numeric entry box] **CHECK what units is this? CHECK - what validation is required?**
- [ ] User will need a way to see the submitted information and potentially edit or cancel **SPLIT STORY OUT**
- [ ] User will need to upload information samples, adapters, tags, lanes and cost codes. See initial table below - needs refining... **LIKELY NEED TO SPLIT OUT**
- [ ] Data will need to be exported to MLWH **SPLIT STORY OUT** **Check with NPG what is required**

Adapter settings file looks something like this.... 
**CHECK - could be just part of the Settings UI above?**
**Consider having separate columns for each lane to simplify validation & parsing and reduce typos**

In a settings file, lines can be commented out with a leading # sign. 

| SettingName | Value | Lanes | 
| ------------- | -----  | ------ |
| R1Adapter | AAAAAAAAAAAAAAAAAAA | 1+2 |    
| R1AdapterTrim | FALSE | 1+2 | 
| R2Adapter | TTTTTTTTTTTTTTTTTTT | 1+2 | 
| R2AdapterTrim | FALSE | 1+2 |   

Sample data file looks something like this:
**Sample Name here will likely need to be Supplier Sample Name? CHECK**

| SampleName | Index1 | Index2 | 
| ------------- | -----  | ------ |
| Adept_CB1 | ATGTCGCT | CTAGCTCG |
| Adept_CB2 | CACAGATC | ACGAGAGT |
| Adept_CB3 | GCACATAG | GACTACTA |
| Adept_CB4 | TGTGTCGA | TGTCTGAC |

Finally, it looks like we need some kind of lane and cost code data - 
**CHECK How is this associated with samples - not quite sure? It doesn't seem like enough data to make the link?**
_Fill in the correct sample schema associated with the Adept Preparation Workflow for all sequenced samples._ 
| ? | ? | ? | Lane | Project
| -- | -- | -- | -- | -- |
| GSU1 | ATCACGTT | TATAGCCT | 1 | 7064
| GSU2 | CGATGTTT | TATAGCCT | 1 | 7064
| GSU3 | TTAGGCAT | TATAGCCT | 1 | 7064
| GSU4 | TGACCACT | TATAGCCT | 1 | 7064
| GSU5 | ACAGTGGT | TATAGCCT | 1 | 7064

**CHECK do we need to validate cost code / project exists already?**

**Additional context**
Sequencing on the Element Aviti is currently done as "Walk Up" faculty drop off pre-made libraries with little to no information and Tris's team load them onto the sequencer, data is automatically output to an area in IRods.
This means there are few checks and balances to ensure the sequencing is successful and has the correct authorisations and agreed costs.
As an interim measure this EPIC adds the functionality to upload sample information about the pre-made libraries into SequenceScape with sufficient granularity that a Sample Sheet for the Sequencer can be generated and NPG can process the raw sequencing data for QC.

**Comment by TWJW-SANGER** [comment]
Closing - following decision to drop the automated walk-up service.
